### PR TITLE
Sprockets2 support and external assets directories

### PR DESCRIPTION
**Pull request by kematzy**
Hi,

FYI.  I have created an updated version of your gem with support for Sprockets2 and the configuration of external asset paths.

The branch is very "ME" specific, so I would probably need to clean it up first in case you would be interested in a pull from it.

Thanks for doing the work in the first place.

Regards, 

Kematzy

### CODE REVIEW

**Comment by mraaroncruz** [comment]
I'm super interested.  This repo has fallen to disrepair because I don't use this in my regular workflow anymore.  
Generalize your solution and I will be happy to merge it in.  
aaron

**Comment by mraaroncruz** [comment]
@kematzy Do you want to update the Readme?

**Comment by kematzy** [comment]
Hi, 

I just had a meeting for a few hours and see you've updated the gem.  Great & Thanks! :-)

I updated my master branch with a few minor CLI output changes. Nothing big.

**Comment by mraaroncruz** [comment]
Pushed.

**Pull request closed without merging**
